#!/bin/bash
# ---------------------------------------------------------------------------
# ssh-del - Command line utilitie to delete old fingerprint from know_hosts
#
# Copyright 2014,  <nikitux@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.
#
# Revision history:
# ---------------------------------------------------------------------------

VERSION="1.0"


if [ "$#" -ne "1" ]; then  
	echo "Usage:  SSH-Del (Number line to delete) " 
	echo "Example: SSH-Del 222"
	exit 1
fi

if [[ -n ${1//[0-9]/} ]]; then
	    echo "Contains letters!"
	    echo "Usage:  SSH-Del (Number line to delete) " 
            echo "Example: SSH-Del 222"
	else
	    echo "Borro"
	     sed -ie "$1d" ${HOME}/.ssh/known_hosts  
fi
